services:
  db:
    image: postgres:latest
    container_name: personel_izin_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: REPLACE_WITH_YOUR_POSTGRES_PASSWORD
      POSTGRES_DB: personeldb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql # '/data' ekini kaldırdık

  api:
    build:
      context: .
      dockerfile: personelizin-backend/Dockerfile
    container_name: personelizin-backend-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=personeldb;Username=postgres;Password=REPLACE_WITH_YOUR_DB_PASSWORD
      - Jwt__Key=REPLACE_WITH_YOUR_JWT_KEY
    ports:
      - "5000:8080"
    depends_on:
      - db

volumes:
  postgres_data: